# Site Settings
title:               "Les Françaises Karaoke"
tagline:             "Les Françaises Karaoke"
description:
baseurl:            #""
url:                #"https://karaoke.lesfrancaises.paris"
#github:
#  url:               "0.0.0.0"
navigation:
- title: About
  url: /about
- title: Blog
  url: /blog
paginate:            900
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate]
